/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Framework: typeof import('./src/components/Framework.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    MatchHistory: typeof import('./src/components/record/MatchHistory.vue')['default']
    MettingPlayersCard: typeof import('./src/components/gaming/MettingPlayersCard.vue')['default']
    PlayerCard: typeof import('./src/components/gaming/PlayerCard.vue')['default']
    RecordButton: typeof import('./src/components/record/RecordButton.vue')['default']
    RecordCard: typeof import('./src/components/record/RecordCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavigation: typeof import('./src/components/SideNavigation.vue')['default']
    UserRecord: typeof import('./src/components/record/UserRecord.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
